print("Hello world")
print("lets make a change after staging the initial version of this file!")
print('making a small change and committing without staging')
name = input('whats your name? ')
print('nice to meet you, ' + name)